RESIZE_IMAGE:
  WIDTH: 1200
EDGE_DETECTION:
  APERTURE: 3
  HIGH_THRESHOLD: 200
  LOW_THRESHOLD: 100
LINE_DETECTION:
  THRESHOLD: 300
  DIAGONAL_LINE_ELIMINATION: true
  DIAGONAL_LINE_ELIMINATION_THRESHOLD_DEGREES: 60
BORDER_REFINEMENT:
  LINE_WIDTH: 3
  WARPED_SQUARE_SIZE: 50
  NUM_SURROUNDING_SQUARES_IN_WARPED_IMG: 1
  SOBEL_KERNEL_SIZE: 3
  EDGE_DETECTION:
    HORIZONTAL:
      APERTURE: 3
      HIGH_THRESHOLD: 200
      LOW_THRESHOLD: 100
    VERTICAL:
      APERTURE: 3
      HIGH_THRESHOLD: 200
      LOW_THRESHOLD: 100
MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE: 0.5
RANSAC:
  BEST_SOLUTION_TOLERANCE: 0.1
  OFFSET_TOLERANCE: 0.1
