RESIZE_IMAGE:
  WIDTH: 1200
EDGE_DETECTION:
  APERTURE: 3
  HIGH_THRESHOLD: 300
  LOW_THRESHOLD: 50
LINE_DETECTION:
  THRESHOLD: 100
  DIAGONAL_LINE_ELIMINATION: true
  DIAGONAL_LINE_ELIMINATION_THRESHOLD_DEGREES: 45
BORDER_REFINEMENT:
  LINE_WIDTH: 4
  WARPED_SQUARE_SIZE: [50, 50]
  NUM_SURROUNDING_SQUARES_IN_WARPED_IMG: 5
  SOBEL_KERNEL_SIZE: 3
  EDGE_DETECTION:
    HORIZONTAL:
      APERTURE: 3
      HIGH_THRESHOLD: 250
      LOW_THRESHOLD: 80
    VERTICAL:
      APERTURE: 3
      HIGH_THRESHOLD: 150
      LOW_THRESHOLD: 60
MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE: 0.5
RANSAC:
  BEST_SOLUTION_TOLERANCE: 0.2
  OFFSET_TOLERANCE: 0.15
